[2022-12-18T00:23:50.854+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: postgres_with_airflow.create_table_task manual__2022-12-17T06:22:10.720013+00:00 [queued]>
[2022-12-18T00:23:50.967+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: postgres_with_airflow.create_table_task manual__2022-12-17T06:22:10.720013+00:00 [queued]>
[2022-12-18T00:23:50.968+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-18T00:23:50.988+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2022-12-18T00:23:50.988+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-18T00:23:51.192+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_table_task> on 2022-12-17 06:22:10.720013+00:00
[2022-12-18T00:23:51.272+0000] {standard_task_runner.py:55} INFO - Started process 275 to run task
[2022-12-18T00:23:51.309+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_with_***', 'create_table_task', 'manual__2022-12-17T06:22:10.720013+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp5pn4gjih']
[2022-12-18T00:23:51.313+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask create_table_task
[2022-12-18T00:23:52.193+0000] {task_command.py:389} INFO - Running <TaskInstance: postgres_with_airflow.create_table_task manual__2022-12-17T06:22:10.720013+00:00 [running]> on host f376bb2680d1
[2022-12-18T00:23:53.052+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_with_***
AIRFLOW_CTX_TASK_ID=create_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T06:22:10.720013+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T06:22:10.720013+00:00
[2022-12-18T00:23:53.058+0000] {sql.py:253} INFO - Executing: 
            CREATE TABLE traffic_data (id INT NOT NULL, track_id INT NOT NULL, type VARCHAR(250) NOT NULL, traveled_d VARCHAR(250) NOT NULL, avg_speed VARCHAR(250) NOT NULL, lat VARCHAR(250) NOT NULL, lon VARCHAR(250) NOT NULL, speed VARCHAR(250) NOT NULL, lon_acc VARCHAR(250) NOT NULL, lat_acc VARCHAR(250) NOT NULL, time VARCHAR(250) NOT NULL);
        
[2022-12-18T00:23:53.193+0000] {base.py:73} INFO - Using connection ID '***_dbt_setup' for task execution.
[2022-12-18T00:24:19.420+0000] {local_task_job.py:159} INFO - Task exited with return code Negsignal.SIGKILL
[2022-12-18T00:24:20.151+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
