[2022-12-16T14:21:22.796+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: postgresoperator_demo.insert_data_task manual__2022-12-16T14:02:43.186476+00:00 [queued]>
[2022-12-16T14:21:22.887+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: postgresoperator_demo.insert_data_task manual__2022-12-16T14:02:43.186476+00:00 [queued]>
[2022-12-16T14:21:22.888+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T14:21:22.890+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2022-12-16T14:21:22.891+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T14:21:23.024+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): insert_data_task> on 2022-12-16 14:02:43.186476+00:00
[2022-12-16T14:21:23.079+0000] {standard_task_runner.py:55} INFO - Started process 316 to run task
[2022-12-16T14:21:23.133+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgresoperator_demo', 'insert_data_task', 'manual__2022-12-16T14:02:43.186476+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/my_new_dag.py', '--cfg-path', '/tmp/tmpnwmp96lp']
[2022-12-16T14:21:23.134+0000] {standard_task_runner.py:83} INFO - Job 31: Subtask insert_data_task
[2022-12-16T14:21:36.759+0000] {task_command.py:389} INFO - Running <TaskInstance: postgresoperator_demo.insert_data_task manual__2022-12-16T14:02:43.186476+00:00 [running]> on host 0d1c0c89de6a
[2022-12-16T14:22:29.889+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgresoperator_demo
AIRFLOW_CTX_TASK_ID=insert_data_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T14:02:43.186476+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-16T14:02:43.186476+00:00
[2022-12-16T14:22:29.942+0000] {sql.py:253} INFO - Executing: 
                insert into employee (id, name, dept) values(1, 'vamshi','bigdata'),(2, 'divya','bigdata'),(3, 'binny','projectmanager'),
                (4, 'omair','projectmanager') ,(5, 'gtyuu','projectmanager') ;
              
[2022-12-16T14:22:30.098+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-12-16T14:24:25.444+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-12-16T14:24:25.620+0000] {sql.py:364} INFO - Running statement: 
                insert into employee (id, name, dept) values(1, 'vamshi','bigdata'),(2, 'divya','bigdata'),(3, 'binny','projectmanager'),
                (4, 'omair','projectmanager') ,(5, 'gtyuu','projectmanager') ;
              , parameters: None
[2022-12-16T14:24:25.659+0000] {sql.py:373} INFO - Rows affected: 5
[2022-12-16T14:24:25.828+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=postgresoperator_demo, task_id=insert_data_task, execution_date=20221216T140243, start_date=20221216T142122, end_date=20221216T142425
[2022-12-16T14:24:26.264+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-16T14:24:26.538+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
